SELECT 
CONCAT(T1.FIRST_NAME, ' ',T1.LAST_NAME) AS 'Nome completo',
T2.JOB_TITLE AS 'Cargo',
T3.START_DATE AS 'Data de início do cargo',
DEPARTMENT_NAME AS 'Departamento'
FROM hr.employees AS T1
INNER JOIN hr.jobs AS T2 ON T1.JOB_ID = T2.JOB_ID
INNER JOIN hr.job_history AS T3 ON T1.EMPLOYEE_ID = T3.EMPLOYEE_ID
INNER JOIN hr.departments AS T4 ON T1.DEPARTMENT_ID = T4.DEPARTMENT_ID
ORDER BY CONCAT(T1.FIRST_NAME, ' ',T1.LAST_NAME) DESC, 'Cargo';
