SELECT t2.JOB_TITLE AS Cargo, ROUND(AVG(t1.SALARY),2) AS 'Média Salarial',CASE
WHEN AVG(t1.SALARY) BETWEEN 2000 AND 5800 THEN 'Junior'
WHEN AVG(t1.SALARY) BETWEEN 5801 AND 7500 THEN 'Pleno'
WHEN AVG(t1.SALARY) BETWEEN 7501 AND 10500 THEN 'Sênior'
WHEN AVG(t1.SALARY) > 10500 THEN 'CEO'
ELSE 'ERRO'
END
AS "Senioridade" FROM employees AS t1
INNER JOIN jobs AS t2
ON t1.JOB_ID = t2.JOB_id
GROUP BY CARGO
ORDER BY `Média Salarial`, Cargo;
