SELECT
  CONCAT(EMPLOYEES.FIRST_NAME, ' ', EMPLOYEES.LAST_NAME) AS `Nome completo`,
  JOBS.JOB_TITLE AS `Cargo`,
  HISTORY.START_DATE AS `Data de início do cargo`,
  DEPARTMENT.DEPARTMENT_NAME AS `Departamento`
FROM
  hr.employees AS EMPLOYEES
  INNER JOIN hr.jobs AS JOBS ON EMPLOYEES.JOB_ID = JOBS.JOB_ID
  INNER JOIN hr.job_history AS HISTORY ON JOBS.JOB_ID = HISTORY.JOB_ID
  INNER JOIN hr.departments AS DEPARTMENT ON HISTORY.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID
ORDER BY
  `Nome completo` DESC,
  `Cargo`;
